repos:
- repo: https://github.com/hootsuite/pre-commit-php.git
  rev: master
  hooks:
    - id: php-cs
      name: PHP Codesniffer
      description: Run php codesniffer against all staged files.
      entry: pre_commit_hooks/php-cs.sh
      language: script
      files: \.php$

    - id: php-cbf
      name: PHP Codesniffer (Code Beutifier and Formatter)
      description: Run php codesniffer against all staged files.
      entry: pre_commit_hooks/php-cbf.sh
      language: script
      files: \.php$

    - id: php-cs-fixer
      name: PHP Coding Standards Fixer
      description: Run php coding standards fixer against all staged files.
      entry: pre_commit_hooks/php-cs-fixer.sh
      language: script
      files: \.php$
